version: '3'
# Replace network name with the fabric test-network name
services:
  redis:
    image: 'redis'
    command: ['--maxmemory-policy','noeviction','--requirepass','${REDIS_PASSWORD}']
    ports:
      - 6379:6379
    networks:
      - viriot_master

  master:
    image: 'viriot/mastercontroller-on-fabric'
    command: ['app']
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD
    networks:
      - viriot_master


networks:
  viriot_master:
    external: true
